### ISSUE TITLE
Install public packages / zip files?

### ISSUE THREAD

**Issue by infertux** [Skinney/elm-git-install#22]
With the recent GitHub outage in mind, I think being able to install public Elm packages from an alternative website would be interesting. Currently the URL is [hardcoded](https://github.com/elm/compiler/blob/master/builder/src/Deps/Website.hs#L301). I wonder if we should make it configurable in the compiler or if this should better handled by a third-party tool such as yours.

Moreover, some packages still show up on package.elm-lang.org but fail to install when you run `elm install` (e.g. `abradley2/form-fields`) because the GitHub repo has been deleted. I've got some spare bandwidth/disk space and would be keen to maintain a mirror of all Elm packages to prevent that kind of issue.

Thoughts?

**Comment by robinheghan** [comment]
Hi, and thank you for your suggestion.

I don't look at `elm-git-install` as a package manager, but a temporary work around to Elm not supporting private packages. As such, your suggestion is unfortunately out of scope for this tool.
