### ISSUE TITLE
Feature request: Gulp plugin

### ISSUE THREAD

**Issue by barbeque** [Skinney/elm-git-install#24]
We're using `elm-git-install` for a small project with two developers, but hopefully more soon. When we bundle the Elm part of the code to use it from the webapp, we use gulp.

The problem we have is that, even with "heads-up" notifications of version bumps, whenever we have a core library update, sometimes we forget to manually run `elm-git-install` in the dependent projects to make sure it actually gets downloaded.

It would be nice to have a gulp plugin that would automatically run `elm-git-install` in the appropriate directory (our `elm-git.json` is nested pretty far into the repo, far away from the Gulpfile) so that we could make sure that we always have the version specified in `elm-git.json` installed before bundling.

**Comment by robinheghan** [comment]
Unfortunately, I don't have any experience with gulp.
I'd be happy to add any features necessary for gulp integration to be a thing, but I'm unable to add it myself due to time constraints.
