### ISSUE TITLE
I get duplicates in source-directories in elm.json

### ISSUE THREAD

**Issue by Matsemann** [Skinney/elm-git-install#25]
`elm-git.json`:

```
{
    "git-dependencies": {
        "direct": {
            "git@github.com:org/module.git": "39.0.0"
        },
        "indirect": {}
    }
}
```

and the existing `elm.json` checked into vcs:

```
    "source-directories": [
        "elm-stuff/gitdeps/github.com/org/module.git/src",
        "src"
    ],
    .....
```

after running `elm-git-install`, it adds a new entry for the installed module in `elm.json`, so it ends up looking like this:

```
    "source-directories": [
        "elm-stuff/gitdeps/github.com/org/module.git/src",
        "elm-stuff\\gitdeps\\github.com\\org\\module.git\\src",
        "src"
    ],
```

My guess is it's because I'm running *Windows*, and it doesn't realize it's the same path it tries to add.
Not a huge deal, right now I just have to revert `elm.json` after running the installation.
But without fixing it I get errors with `ambiguous import ... I found multiple module with that name though`

**Comment by robinheghan** [comment]
I might have a fix on master. Could you try it out and let me know?

**Comment by Matsemann** [comment]
It works better, as it now doesn't duplicate. But it ends up changing the separator at some places and make a diff:

elm.json before:
```
        "elm-stuff/gitdeps/github.com/<org>/<module>.git/src",
```

elm.json after:
```
        "elm-stuff/gitdeps\\github.com\\<org>\\<module>.git\\src",
```

**Comment by robinheghan** [comment]
Would you mind trying again with latest master?

If it doesn't work, could you run the following two statements in the node repl and tell me what the values are?

```
var path = require('path');
path.join('elm-stuff', 'gitdeps');
```

and

```
var path = require('path');
path.join('elm-stuff', 'gitdeps').replace(path.sep, '/');
```

**Comment by Matsemann** [comment]
Same result.

```
$ node
> var path = require('path');
undefined
> path.join('elm-stuff', 'gitdeps');
'elm-stuff\\gitdeps'
```
```
$ node
> var path = require('path');
undefined
> path.join('elm-stuff', 'gitdeps').replace(path.sep, '/');
'elm-stuff/gitdeps'
```

Maybe try `upath` 🤔 

```
> var upath = require('upath')
undefined
> upath.join('elm-stuff', 'gitdeps')
'elm-stuff/gitdeps'
```

**Comment by Skinney** [comment]
Interesting. What happens if you modify the script to use `upath` instead of `path`?

**Comment by robinheghan** [comment]
Master now uses `upath`, does it work now?

**Comment by Matsemann** [comment]
Yup, no diff in `elm.json` now 👍

**Comment by robinheghan** [comment]
Smud. I'll cut a new release later today :)
