### ISSUE TITLE
git@github.com: Permission denied (publickey).

### ISSUE THREAD

**Issue by MartinSStewart** [Skinney/elm-git-install#27]
When running `elm-git-install` I get the following output 
```
$ yarn run elm-git-install
yarn run v0.16.1
$ "/Users/martinstewart/Desktop/surface-voyager/node_modules/.bin/elm-git-install" 
Cloning into 'elm-stuff/gitdeps/github.com/MartinSStewart/elm-obj-loader.git'...
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Cloning into 'elm-stuff/gitdeps/github.com/MartinSStewart/elm-obj-loader.git'...
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

✨  Done in 0.95s.
```
My `elm-git.json` looks like this 
```
{
  "git-dependencies": {
    "direct": {
      "git@github.com:MartinSStewart/elm-obj-loader.git": "2.0.0"
    },
    "indirect": {
    }
  }
}
```

This is on MacOS Catalina and I'm using Elm 0.19.1

**Comment by robinheghan** [comment]
Does `git clone git@github.com:MartinSStewart/elm-obj-loader.git` work?

**Comment by MartinSStewart** [comment]
Hmm, no it doesn't. I was able to clone the project with gitkraken so I assumed that wasn't the issue. I guess gitkraken is doing something differently. I guess the issue is on my end then but I'll update you once I know for certain.

**Comment by MartinSStewart** [comment]
I replaced `git@github.com:MartinSStewart/elm-obj-loader.git` with `https://github.com/MartinSStewart/elm-obj-loader.git` and now it works. I don't understand git well enough to understand why but I'll take it!

**Comment by robinheghan** [comment]
The first method uses ssl instead of https, which requires that you have to have your ssh keys setup properly.
