### ISSUE TITLE
Treat github packages like actual packages

### ISSUE THREAD

**Issue by MartinSStewart** [Skinney/elm-git-install#28]
The current implementation of elm-git-install adds a `source-directories` path in the elm.json rather than adding an entry into the `direct` dependencies list. The problem with this approach is that it doesn't respect the github package's `exposed-modules`. The user can unintentionally import modules that they shouldn't have access too. 

Additionally, adding a path to `source-directories` means that any dependencies of that package become `direct` dependencies in the application rather than `indirect` dependencies.

**Comment by robinheghan** [comment]
It's not possible to add an entry into the `direct` dependencies list. Elm will interpret this as if the package exists at `https://package.elm-lang.org`, and so fail to compile.

`elm-git-install` is a work around for missing functionality in Elm proper, and so it will never be as good as native support for private packages.

**Comment by MartinSStewart** [comment]
That's a shame. Thanks anyway for this tool, it's certainly better than my previous technique of copying package source code into my project.
